application: helpouts-graph
version: 1
runtime: python27
api_version: 1
threadsafe: yes

libraries:
- name: webapp2
  version: "2.5.2"

skip_files:
- ^(.*/)?app\.ya?ml
- ^(.*/)?index\.ya?ml
- ^(.*/)?#.*#
- ^(.*/)?.*~
- ^(.*/)?.*\.py[co]
- ^(.*/)?.*/RCS/.*
- ^(.*/)?\..*
- ^(.*/)?.*\.haml
- ^(.*/)?.*\.scss
- ^(.*/)?.*\.less
- ^/docs*

handlers:
- url: /favicon.ico
  static_files: application/static/img/favicon.ico
  upload: application/static/img/favicon.ico

- url: /st
  static_dir: application/static
- url: /st/css
  static_dir: application/static/css
- url: /st/js
  static_dir: application/static/js

# Main script
- url: .*
  script: run.app
